### ISSUE TITLE
Separate apps should be in separate repositories

### ISSUE THREAD

**Issue by basilveerman** [pacificclimate/climate-explorer#13]
Current, the back end and front end are in separate directories within this repository. While they were originally dependant on each other and this was easy for management, the code bases are now completely independent. This should be reflected in the repository management.

I propose splitting the back end and front end into separate repositories and reducing this repository to just the 2 submodules and some deployment information.

Thoughts @jameshiebert, @mdfischer ?

**Comment by jameshiebert** [comment]
I think that this makes a lot of sense, especially since there's essentially zero interaction between the two which isn't over the web API. The only downside that I would see is that we can't do any in-repo integration tests, but we don't actually do any now, anyway. So, we could split the two apart, and then have a separate repo layered on top with a Docker container that stands up both of them and runs integration tests.
